CREATE TABLE category (
    id int NOT NULL AUTO_INCREMENT,
    name varchar(255),
    description varchar(1000),
    image varchar(255),
    PRIMARY KEY (ID)
);

CREATE TABLE subcategory (
    id int NOT NULL AUTO_INCREMENT,
    lat float(10,6) NOT NULL,
    lng float(10,6),
    name varchar(255),
    description varchar(10000),
    image varchar(255),
    categoryid int(20),
    image02 varchar(255),
    image03 varchar(255),
    PRIMARY KEY (ID)
);


CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO `category`(`id`, `name`, `descriptions Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`, `image`) VALUES 
    ('1','temples','all the temples','https://risingnepaldaily.com/banner_image/5ea0e5798a68e_pas.png'),
    ('2','hospital','all the hospital','https://media.istockphoto.com/photos/building-with-large-h-sign-for-hospital-picture-id1130389312?k=6&m=1130389312&s=612x612&w=0&h=qqIDfSODZ489SOMAdJUxTQt4uwd-2zagN_fi8t4-UeY='),
    ('3','resturants','all the resturant','https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Restaurant_N%C3%A4sinneula.jpg/1200px-Restaurant_N%C3%A4sinneula.jpg'),
    ('4','bus stations','all the bus stations','https://upload.wikimedia.org/wikipedia/commons/6/6e/Bath_Bus_Station_First_66729_WX54XCO_42910_WX05RVU.jpg'),
    ('5','shopping mall','all the shopping mall','https://assets.publishing.service.gov.uk/government/uploads/system/uploads/image_data/file/111994/s960_EmptyClassroom.jpg'),
    ('6','parks','all the parks','https://nepmag.net/wp-content/uploads/2018/05/26230189_1830268730348306_3964558406324177448_n.jpg'),
    ('7','hiking places','all the hiking places','https://nepmag.net/wp-content/uploads/2018/05/26230189_1830268730348306_3964558406324177448_n.jpg');
    ('8','theaters','all the theaters','https://nepmag.net/wp-content/uploads/2018/05/26230189_1830268730348306_3964558406324177448_n.jpg');




INSERT INTO `subcategory`(`id`, `lat`, `lng`, `name`, `description`, `image`, `categoryid`, `image02`, `image03`) VALUES 
    ('1','27.710501','85.348701','PASHUPATINATH TEMPLE','Pashupatinath is more than just a religious destination. It is a combination of religion, art, and culture. It offers peace and devotion. The temple, spread across 246 hectors of land abounds in temples and monuments. Hundreds of rituals are performed here every day. The temple premises is an open museum. This national treasure was designated a UNESCO World Cultural Heritage Site in 1979. This temple is an important destination for art historians. It displays a variety of temple design some of which are Dome style, Pagoda style, Shikhara style and so on. Additionally there are varieties of statues and sculptures around the complex. There are statues made out of stone, metal, and wood. The door and pillars around the temple area are carved in beautiful shapes of God and griffins.', 'https://www.welcomenepal.com/uploads/Pashupatinath2_sm_pilgrims1.jpg','1','https://www.welcomenepal.com/uploads/Pashupatinath_tk_pilgrims.jpg','https://www.welcomenepal.com/uploads/destination/pashupatinath-sm-pilgrims.jpeg'),
   	('2','27.714800','85.290398','SHYAMBHUNATH','The Swayambhunath Stupa is one of the crowning glories of Kathmandu Valley architecture. This perfectly proportioned monument rises through a whitewashed dome to a gilded spire, from where four iconic faces of the Buddha stare out across the valley in the cardinal directions. The site was shaken severely by the 2015 earthquake, but the main stupa sustained only superficial damage.
    The entire structure of the stupa is deeply symbolic: the white dome represents the earth, while the 13-tiered, tower-like structure at the top symbolises the 13 stages to nirvana. The nose-like squiggle below the piercing eyes is actually the Nepali number ek one, signifying unity, and above is a third eye signifying the all-seeing insight of the Buddha.The base of the central stupa is ringed by prayer wheels embossed with the sacred mantra om mani padme hum (‘hail to the jewel in the lotus’). Pilgrims circuiting the stupa spin each one as they pass by. Fluttering above the stupa are thousands of prayer flags, with similar mantras, which are said to be carried to heaven by the Wind Horse. Set in ornate plinths around the base of the stupa are statues representing the five Dhyani Buddhas – Vairocana, Ratnasambhava, Amitabha, Amoghasiddhi and Aksobhya – and their consorts. These deities represent the five qualities of Buddhist wisdom.
    ', 'https://www.welcomenepal.com/uploads/destination/swayambhu-leisure-1.jpeg','1','https://www.welcomenepal.com/uploads/destination/swayambhu-leisure-1.jpeg','https://1.bp.blogspot.com/-kJQlFX98XyY/V3ZhzOHSgxI/AAAAAAAAAB8/FjHl2cW72yIlawNCNTcrpC8QTFFxGQ87gCLcB/s1600/Swayambunath2.jpg'),
    ('3','27.721500','85.362000','BOUDHANATH','Take an early morning or evening stroll around the inspiring white dome buzzing with energy; observe the devout people circumambulating, light a butter lamp and say a little prayer, look around for souvenirs, or enjoy the view from a rooftop restaurant with a hot cup of cofee. Boudha is always full of life.
    Situated 8 km to the east of downtown Kathmandu, Boudha,  is one of the UNESCO World Heritage sites and one of the most imposing landmarks in Kathmandu. Visible as soon as you land at the Tribhuvan International Airport, it is the largest stupa in the Kathmandu Valley.
    The 36-meter-high stupa of Boudha is massive and dominates the skyline in the area. With countless monasteries around it, Boudha is the center of Tibetan Buddhism in Nepal.
    Built in the shape of a mandala designed to replicate the Gyangtse of Tibet, the stupa was renovated by Licchhavi rulers in the 8th century. The location of the stupa is interesting as it once lay on the ancient trade route to Tibet and it was here that Tibetan merchants rested and offered prayers for many centuries. It is one of the major pilgrimage sites for Buddhists from around the world.
    On each side are the all-seeing-eyes of the Buddha symbolizing awareness. The canopy has 13 stages. At ground level there is a brick wall that has 147 niches and 108 images of the meditational Buddha inset behind copper prayer wheels.
    ', 'https://www.welcomenepal.com/uploads/destination/bauddha-sb-lt.jpeg','1','https://i2.wp.com/www.elitetreks.com/wp-content/uploads/2018/07/the-great-boudha-stupa.jpg?w=1920&ssl=1','https://st.depositphotos.com/2942447/5176/i/950/depositphotos_51767481-stock-photo-boudhanath-stupa-in-kathmandu-nepal.jpg'),
    ('4','27.676580','85.314171','KRISHNA TEMPLE', 'Krishna is believed to be an earthly incarnation of Vishnu; hence, images of Vishnu and his mount, Garuda, are found throughout the temple. Four full-size statues of Vishnu upon Garuda surround the base of the sikhara, while bas-reliefs of the same theme are located on the ground floor cornices. Depictions of the 10 avatars of Vishnu are also set on the outside face of the ground-level gallery. A freestanding statue of gided Garuda, mounted upon a pole, is set in front of the temple. It was erected by Siddhi Narasingh Malla about ten years after construction of the temple.
    The Krishna Mandir is managed by local Brahmins and is still used, though entrance is forbidden to non-Hindus (as was the case with the nearby Bhimsen temple, currently awaiting restoration as it was completely destroyed in the 2015 earthquake).
    The temple was hard-hit by the 2015 earthquake, sustaining structural damage, particularly to its upper floors. It was painstakingly restored by the Kathmandu Valley Preservation Trust (KVPT) at the cost of 5.7 million Nepali rupees (~$55,000 USD) and reopened to pilgrims and tourists in 2018.',
    'https://www.orientalarchitecture.com/gallery/nepal/patan/krishna-mandir-temple/photos/krishna-mandir01.jpg','1','https://www.orientalarchitecture.com/gallery/nepal/patan/krishna-mandir-temple/photos/krishna-mandir04.jpg','https://www.orientalarchitecture.com/gallery/nepal/patan/krishna-mandir-temple/photos/krishna-mandir02.jpg'),
    ('5','27.703300','85.432404','CHANGUNARAYAN TEMPLE','description of muktinath temple', 'https://www.holidify.com/images/cmsuploads/compressed/8568905000_b259fb2088_b_20190503201520.jpg','1','http://photos.wikimapia.org/p/00/03/95/16/07_big.jpg','http://photos.wikimapia.org/p/00/00/86/77/60_big.jpg'),
    ('6','27.5711', '85.4056','PHULCHOWKI HIKE','Height: 2,782m
    Highlights: Sub-tropical forest, breathtaking views of the Kathmandu Valley and views of Annapurna and Gaurishankar mountains.
    Hike Duration: 6.5 to 7 hours
    Phulchowki is the highest hill near Kathmandu and is situated to the south of the city. To get there you need to drive to Godawari (14 km south of Kathmandu), where you start the hike. You will be able to see sub-tropical thick forests filled with rhododendrons and oak trees as well as several species of orchids, butterflies, and birds. From the top you get a breathtaking view of the valley and on clear days you can see the eastern parts of the Annapurna range to Gaurishankar in the east. While you are there, why not check out the Botanical Gardens in Godawari.
    ', 'https://www.eyesonnepal.com/wp-content/uploads/2018/09/Phulchowki-Hike.jpg','7','https://yatrinepal.com/sites/default/files/styles/cover/public/phulchwoki.jpg?itok=ASVIpxqT','https://www.khojnu.com/wp-content/uploads/2027/03/Phulchowki-Hill.png'),
    ('7','27.6462','85.2532','CHAMPADEVI HIKE','Height: 2,249
    Highlights: Smell off the pine forests! Stupas and monasteries.
    Hike Duration: depending on the route, 3 to 6 hours.
    Champadevi is in the southeastern corner of the Kathmandu Valley and is technically in Makwanpur District. There are several routes to reach the summit, but the most popular, and easiest to access is one that takes you along the Dollu Valley through pine forests and along the grassy ridge top. This route starts from Hattiban Resort and the trail is well trodden and easy to follow. From the resort, the trip will take around three hours, there and back. Parking is available at the bottom of the steep, gravel road to the resort (for bigger vehicles or if you want extra walking time) or at the resort itself.
    A less used and longer route begins just after the Dakshinkali Temple road, beyond Taudaha Lake. This route sees you walking along dirt roads through fields until you reach the forest where the trail climbs steeply through the forest to reach the ridge above Haatiban Resort.  This will take you from 4 to 6 hours.', 'https://nepalguidetrekking.com/uploads/package/frontend/1-Day-Champadevi-Hike-1-Day','7','https://www.thirdrockadventures.com/assets-back/images/trip/champadevi-hiking-trail.jpgTNd.jpg','https://www.luxuryholidaynepal.com/uploads/img/day-hike-to-champadevi-hill-from-kathmandu_1522135553.jpg'),
    ('8','27.7174','85.5046','NAGARKOT','Height: 2,195m
    Highlights: from Nagarkot and its surrounding hills you can see several mountain ranges including Annapurna, Ganesh Himal, Langtang and Everest. Sunrise and sunset from Nagarkot.
    Hike Duration: 4 hours
    Nagarkot itself is 32km east of Kathmandu and can be visited for a day but in order to really appreciate the beauty of the area and mountain views, it is a good idea to hike around the area and, if possible, stay overnight.
    To start your trek drive approximately one hour to Sakhu, an ancient Newari town on the northeast corner of the Kathmandu Valley. The hike takes approximately four hours through pine forests. On reaching Nagarkot you can look around the village and watch the sun set spectacularly over the Himalayas. Then take a (pre-booked) taxi back to Kathmandu or stay overnight and hike down or take a local bus down the next day. And don’t forget the even more spectacular sunrise!', 'https://www.luxuryholidaynepal.com/uploads/img/nagarkot-changunarayan-day-hike_1489720805.jpg','7','https://www.mountainmonarch.com/uploads/img/nagarkot-changunarayan-hike.jpg','https://media.tacdn.com/media/attractions-splice-spp-674x446/07/29/ea/cd.jpg'),
    ('9','28.6353','81.2774','CHISAPANI HIKE','Height: 2,215m
    Highlights: Hike through Shivapuri National Park sub-tropical forest. Views of Langtang Himal, Ganesh Himal, Jugal Himal and Gaurishankar Himal ranges
    Hike Duration: 4 to 5 hours
    Chisapani is a small settlement of Brahmin, Gurung and Sherpa with fantastic views and good hiking around it. The hike starts from Sundarijal (around an hour from central Kathmandu), passes the main water source for Kathmandu and goes on through Shivapuri National Park until you reach Chisapani village.', 'https://475418-1493271-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2017/12/kathmandu-chisapani-hike.jpg','7','https://www.outdoorhimalayan.com/wp-content/uploads/2018/03/sundarijal-chisapani-nagarkot-hike-nepal-outdoorhimalayan-treks-5-730x450.jpg','https://www.himalayadarshantreks.com/wp-content/uploads/2018/09/Chisapani-Trek.jpg'),
    ('10','27.7174','85.5046','CHISAPANI TO NAGARKOT','A good way to expand your trek to Chisapani is to keep on going the next day to Nagarkot. Trek Sundarijal to Chisapani as described above, overnight then hike approximately 7 hours through mostly dense forest to Nagarkot, where you can overnight again or drive directly back to Kathmandu.
    Another alternative is to keep trekking from Nagarkot to Changunarayan (that day or the next) and then drive back to Kathmandu.
    The trail from Nagarkot to Changunarayan descends through terraced fields, through a Tamang village and on along a ridge of deciduous forest.
    From Nagarkot to the temple at Changunarayan it takes about 4 hours. This temple is a UNESCO World Heritage Site, which has been resorted after being damaged in the 2015 earthquakes. There is also a very interesting museum at the temple which has been lovingly cared for over the years.
    ', 'https://www.asianhikingteam.com/assets/images/langtang/chisapani-nagarkot-trek.jpg','7','https://475418-1493271-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2017/12/nagarkot-chisapani-hiking.jpg','https://475418-1493271-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2017/12/nagarkot-chisapani-hiking.jpg'), 
    ('11', '27.7046702', '85.3424033' ,'Krisharpan Nepali Restaurant','A restaurant where culture is very well portrayed. This is a 9 course meal. Yes it takes time and the menu is elaborate, but if you have good company then time flies. The portion is small and appropriate for a 9 course meal. Service and quality is worth the money paid. The meal (veg and non veg set menu) ranges from a 6 to 22 course set dinner menu which can cost upto a USD 90 per head. We took the 6 course set menu and loved this traditional meal. They served us a personalised dinner menu and started','https://media-cdn.tripadvisor.com/media/photo-s/03/e9/37/59/krishnarpan-restaurant.jpg','3',
    'https://media-cdn.tripadvisor.com/media/photo-s/03/e9/36/60/krishnarpan-restaurant.jpg','https://media-cdn.tripadvisor.com/media/photo-s/03/e9/37/59/krishnarpan-restaurant.jpg'),
    ('12', '27.7046702', '85.3424033' ,'Kathmandu Grill Restaurant & bar','This Kathmandu grill restaurant and wine bar garden was perfect. impressed and parking also huge campare to the  thamel area off course food and beverage also reasonable price kitchen and service (all the staff) service is great. 27.7185966 85.3078603 
    ','https://media-cdn.tripadvisor.com/media/photo-s/06/96/82/e5/kathmandu-grill.jpg','3','https://media-cdn.tripadvisor.com/media/photo-s/03/f8/cf/80/kathmandu-grill.jpg ','https://media-cdn.tripadvisor.com/media/photo-s/03/f8/cf/80/kathmandu-grill.jpg'),
    ('13', '27.7120863' ,'85.3155623','The Chimney Restaurant','All of our dining options have one thing in common, delicious food made from healthy, ingredients prepared by our devoted chefs. We proudly source regional and organic products and buy from speciality suppliers to bring our diners the healthiest, tastiest cuisine we can. Before or after your meal, our lively bar offers a wide array of cocktails, beers and wines to suit any thirst.','https://www.yakandyeti.com/templates/yootheme/cache/intro-chimney-c78f1a1a.jpeg','3','https://www.yakandyeti.com/templates/yootheme/cache/spice-room-intro-83ed1d6a.jpeg','https://www.yakandyeti.com/images/dining/chimney/chimney-outdoor-4.jpg '),
    ('14', '27.7024949','85.311008' ,'Bhojan Griha','The 150 year old heritage, Bhojan Griha was started to give an example to the government that old buildings need to be respected. The building was in a very dilapidated state and going to be demolished, so in 1998 Bharat Basnet took over the building previously resided by the Royal Priest of The King of Nepal and completely renovated it. The goal was to take locals and use traditional methods and materials to construct buildings to experience the feeling of the past whilst enjoying the music and food in Nepal. “What we eat is what we are” – we work with Chi philosophy to discourage chemical/commercial farming practices. We are constantly working with local producers to encourage traditional/organic way of farming.  Dine to experience Nepali cuisine in a 150 year old heritage building which housed the late Royal Priest of the King of Nepal. You will be served with food prepared from local organic sources from our very own farm. Elevate your senses with the folk dance and music of Nepal! ','https://www.bhojangriha.com/images/banners/bhojan-griha-kathmandu-building.jpg','3','https://www.bhojangriha.com/images/banners/bhojan-griha-kamasutra-bar-kathmandu-banner.jpg','https://www.bhojangriha.com/images/banners/bhojan-griha-kathmandu-nepali-cultural-program-banner.jpg'),
    ('15', '27.7024949','85.311008' ,'Mulchowk Restaurant','In the beautiful main courtyard (Mul Chowk in Nepali) of Babar Mahal Revisited, Mul Chowk provides to all a unique experience bringing culinary art closer to all other forms of culture.
    Whether a quiet lunch meeting, or celebrations we offer fine dining with a refined twist. Serving continental a la carte, elegant cocktails and lavish customized menus for your events, the Mul Chowks team is here to serve you on any occasion.
    THE CHOWK: In days gone by, Chowk (the main courtyard) in homes and places was centre of community activities. Mul Chowk restaurant, as a classic piece of architecture, aspires to bring back the cultural relevance of the Chowk.
    THE RESTAURANT: Shaded under the sanctified Rudraksha tree, the southern orientation of Mul Chowks courtyard ensures yearly sunshine and light, making it a perfect location for lunches and brunches.
    It holds musical concerts and performances of various kinds. When booked for events, Mul Chowk can accommodate up to 200 guests. The menus varies from Continental to Indian depending on your needs. The palace is also available for corporate functions with a complete boardroom set up. Mul Chowk provides lunch boxes and delivers food within Kathmandu. 
    ','https://pagevamp-uploads.s3.amazonaws.com/users/395181273869074/f8815d3157f140b2bc748a337d3e881a.jpg','3','https://ktmguide.com/wp-content/uploads/2019/09/b5.jpg','https://media-cdn.tripadvisor.com/media/photo-s/03/af/f0/80/mulchowk-restaurant.jpg'),
    ('16', '27.7066867','85.3170543' ,'Medicare National Hospital & Research Center','Existing health service facilities in Nepal are still insufficient to meet the growing need of reliable health care. This is why a significant number of patients are going to different hospitals of neighboring countries like India and Thailand for treatment. Ultimately this causes drainage of huge amount of foreign exchange from Nepal and great inconvenience to patients and their relatives. Urgent need for establishment of well equipped and reliable health care centre of international standard has always been felt. ','','2','',''),
    ('17', '27.7066867','85.3170543','Grande City Hospital','Grande City Hospital (P) Ltd is a 24 beds world class health care facility at Jyoti Bhawan, Kantipath -right in the heart of the Kathmandu city. Initially established as Grande City Clinic & Diagnostic Service in 2013, the hospital provides quality health care with state-of-the-art and latest technologies combined with the expertise of highly qualified and trained doctors and professionals.
    The main purpose of the hospital is to provide world-class healthcare facilities in a compassionate environment with optimum utilization of modern technologies. ','https://ktmguide.com/wp-content/uploads/2019/12/5a801c5278950.jpg 
	','2','	https://assets-cdn.kathmandupost.com/uploads/source/news/2019/health/09302016_GRANDE_HOSPITAL__MG_7988.jpg ','	https://myrepublica.nagariknetwork.com/uploads/media/G_20200523155316.jpg'),
    ('18', '27.7066867','85.3170543' ,'Bir Hospital','Bir Hospital is the oldest hospital of Nepal. This hospital was established in 1947 BS, under the name of contemporary Prime Minister Bir Shamsher Jung Bahadur Rana. Initially it was a seven bed hospital with 5 staffs. Today it has a proud history of 125 years and the first hospital of Nepal wherethe practice of modern medicinecommenced.Till eighties services including gynaecology, paediatrics and psychiatry were available in this very hospital. With the evolvement of super specialtyand increasing workload in the limited premises these services were shifted to Indra Rajya Laxmi Devi Shah Maternity hospital Thapathali, Kanti Bal hospital Maharajgunja and Patan mental hospital Lalitpur respectively.
    This is a historical hospital as every modern medical service in the country has roots in this hospital. This is the first hospital where neurosurgery was started in the times when CTscan was not around. In the field of modern cardiology Nepal’s first case of angiography, cathlab and valve replacement were all done at Bir Hospital. Every senior doctor who was a pioneer in the field of modern medicine in Nepal like Dr. Mrigendra Raj Pandey, Dr. Anjani Kumar Sharma, Dr. Dinesh Nath Gongal, Dr. Shabitri Gurung, Dr. Dibyashree Malla, Dr Sudip Kumar Bhattacharya, Dr. Mohin Shah, Dr. Puskar Satyal, Dr. Ishor Lal Acharya, Dr. Dhrub Lal Singh, Dr. Dambar Bahadur Karki, Dr. Sachche Kumar Pahadi, Dr. Dharma Sharan Manadhar, Dr. Ram Prasad Pokharel, Dr. Yanta Mani Pradhan, Dr Ram Bhadra Adiga, Dr. LN Prasad, Dr. JP Rijal, Dr. Jwala Raj Pandey, Dr. Basant Lal Shrestha, Dr. Gopal Achary, Dr. Hemanga Dixit, Dr. Shankar Bahadur Shrestha, Dr. NB Amatya, Dr. Laxman Paudel hadstarted their careers in this hospital. These pioneers are the heroes and the legends of modern medicine in Nepal. Bir hospital is the central hospital where services were provided the royal family members in past.  
    ','https://nams.org.np/images/bir.jpg  ','2','https://assets-cdn.kathmandupost.com/uploads/source/news/2019/miscellaneous/Bir_Hospital-21112018065706-1000x0.jpg  ','https://i0.wp.com/www.peoplesreview.com.np/wp-content/uploads/2021/05/Bir-Hospital.jpg'),
    ('19', '27.7467476','85.3405063' ,'Shahid Gangalal National Heart Center','Shahid Gangalal National Heart Centre (SGNHC) is a hospital which provides cardiac care, diagnostic and treatment procedures in Kathmandu, Nepal.[1][2] The hospital is named after Gangalal Shrestha.[2] It is the first cardiac tertiary center in Nepal. 
    ','https://upload.wikimedia.org/wikipedia/commons/3/3f/Shahid_Gangalal_National_Heart_Centre1.jpg 
	','2','https://ktmguide.com/wp-content/uploads/2020/04/g2.jpg ','https://ktmguide.com/wp-content/uploads/2020/04/g7.jpg '),
	('20', '27.7467476','85.3405063' ,'Upendra Devkota Memorial National Institute Of Neurological And Allied Sciences','Upendra Devkota (18 December 1953 – 18 June 2018) was a Nepali neurosurgeon and founder of the first neurological trauma unit in Nepal, located at Bir Hospital. He held the post of Minister for Health, Science and Technology, Government of Nepal. Devkota was the founder of the National Institute of Neurological and Allied Sciences.
    He was born in Gorkha in 1953 and received his high school education in amar Jyoti Janata High School (commonly known as Luintel High School of Gorkha), Palungtar, Gorkha, Nepal. He was a classmate friend of Baburam Bhattarai from class eight to Isc.[1] He did intermediate of sciences (I Sc) education from Amrit Science college, Tribhuvan University, Kathmandu, Nepal and got Colombo Plan fellowship to pursue medical education in India. He completed Bachelor of medicine and bachelor of surgery (MBBS) in 1978 from Assam Medical College, Dibrugarh, Assam, India and worked some years in Bir Hospital under Dr DN Gongol. He had also been a Health Minister of then His Majesty government of Nepal.
    For advanced training in neurosurgery, he went to the United Kingdom, where he trained at Atkinson Morley Hospital (now part of St Georges Hospital), Southern General Hospital Glasgow. He returned to Nepal in 1989 and started Neurosurgery in Bir Hospital. He established NINAS in Bansbari, Kathmandu, Nepal.  ','
	https://myrepublica.nagariknetwork.com/uploads/media/2018/June/neuro-hospital.jpg ','2','https://neuro.org.np/userfiles/files/hospital.jpg ','https://i.ytimg.com/vi/aehvicqLUwU/maxresdefault.jpg'),
    ('21', '27.732436','85.2993738' ,'Gongabu New Bus Station','bus station at','','4','',''),
    ('22', '27.7067801','85.3059938' ,'Ratna Park Bus Stop','bus station at','','4','',''),
    ('23', '27.7273791','85.348253' ,'Bhrikuti Chowk Bus Stop','bus station at','','4','',''),
    ('24', '27.6939479','85.2761156' ,'Kalanki Bus Stop','bus station at','','4','',''),
    ('25', '27.6678603','85.2980554' ,'Ekantakuna Bus Stop','bus station at','','4','',''),
    ('26', '27.693898','85.3042413' ,'Tripureshwor Bus Stop ','bus station at','','4','',''),
    ('27', '27.7094','85.52626' ,'CITY CENTER','Located centrally in the heart of Kathmandu in Kamal Pokhari, City Center is a shoppers delight.NLIC City Centre is Nepals first integrated family centre located at the heart of Kathmandu, comprising of five floors, full of clothing stores as well as food and entertainment facilities which adds a very blissful experience to the visitors. It is a centrally air conditioned mall, with CCTV, smoke detector, fire alarm, fire hydrant, sufficient power supply with 24 hours generator backup, lively open space at the exterior with a long footpath fitted with light poles, up- to date toiletries and toiled facilities for handicapped people. All shops have tempered glass to lubricate window-shopping. There is also accessibility to telephone line and broad band internet service in every shop.
    ','https://kathmanduo.smugmug.com/BlogPosts/82011/i-DbPTHKx/0/M/IMG0178-M.jpg
    ','5','https://fastly.4sqi.net/img/general/600x600/iN27k_f-w3JAV11zMaeaREETeVxzEjapmpcHXP4TGxk.jpg
    ','https://c8.alamy.com/comp/EDCY7F/interior-of-city-center-mall-at-christmas-kingdom-of-bahrain-EDCY7F.jpg
    '),
    ('28', '27.7146','85.3119' ,'CIVIL MALL','Civil Mall is a 6th storeyed shopping mall established in 2010 with double basement parking, branded clothing stores, movie theater, food court, and kids playing zone. The futuristic mall is located in Sundhara, making it easily accessible from all parts of Kathmandu valley. The mall is equipped with security cameras, smoke detectors, an electricity generator, 14 escalators, 2 capsule lifts, 2 elevators, and 3 stairways running up the building.

    Civil Mall provides a great experience whether for shopping or entertainment. The atrium is designed in a way that visitors can see most of the retail stores without any difficulty. There are more than 175 stores and 10,000 square foot area dedicated to the food court. The mall features a food court with indoor and outdoor seating, that offers varieties of food items from Indian to Japanese. They play live music every Friday and Saturday. The mall has a VR Chair which is a motorized chair with 12D cinema giving a realistic effect. Virtual Reality games can also be played in Civil Mall. The Bal Sansar section of the mall is the largest indoor playing area for kids in Kathmandu. It offers a ball pool, physical activities, and arcade games.

    ','https://i0.wp.com/fra1.digitaloceanspaces.com/appharuspace/notesnepal/uploads/2020/08/civil-mall-sundhara.jpg?fit=800%2C529&ssl=1
    ','5','https://ktmguide.com/wp-content/uploads/2019/09/civil1.jpg
    ','https://c8.alamy.com/comp/M0YCN6/people-visit-civil-mall-shopping-complex-in-kathmandu-nepal-M0YCN6.jpg
    '),
    ('29', '27.6772','85.3170' ,'LABIM MALL','Labim Mall spread over 200,000 square feet brings a world-class shopping experience to Nepal. With QFX cinemas, astonishing variety of cuisine and over 70 top notch brands, it captures the spirit and spacious street style of a global lifestyle with the charm and authentic spirit of Nepal. It is located in Pulchowk, Lalitpur, Nepal.

    Labim Mall is elegant by keeping modernity in mind and is also motivated by traditional Nepalese values of hospitality, kindness and reverence. You’ll experience a unique shopping delight at over 200, 000 square feet. Labim Mall finds shopping privileges for customers of 70 premium brands and a world of luxury accessories where their masterpieces are shown by cutting-edge brands. In addition, it also has a number of exciting locations that will keep you busy throughout your day!

    ','https://media-cdn.tripadvisor.com/media/photo-m/1280/15/65/10/97/caption.jpg
    ','5','https://adesignpro.com/wp-content/uploads/2018/07/Labim-Mall-02-1.jpg
    ','https://ktmguide.com/wp-content/uploads/2019/11/DSC_2716-scaled.jpg
    '),
        ('30', '27.7105','85.3179' ,'SHERPA MALL ','Sherpa mall is a shopping mall located in durbar marg.Located in Durbar Marg, Sherpa Mall is especially popular with the young adult crowd as it offers a good mixture of dining and shopping.Sherpa mall provides you with the facilities of proper shopping of Clothing, Shoes, Fashion Accessories , Gadgets,Sports Accessories and many more.Sherpa Mall is also a renowned Shopping & Hang out destination.
    ','https://ktmguide.com/wp-content/uploads/2019/09/xsherpa-mall-1234-550x410.jpg.pagespeed.ic.v-aolFUyYQ.webp
    ','5','https://ktmguide.com/wp-content/uploads/2019/09/xsherpa-mall-550x410.jpg.pagespeed.ic.ohF_SAW-t_.webp
    ','https://ktmguide.com/wp-content/uploads/2019/09/xsherpa-mall-1-550x410.jpg.pagespeed.ic._mTTAuSqI4.webp
    '),
        ('31', '27.7161','85.2841' ,'AMIDEVA BUDDHA PARK','Amideva Buddha Park features three giant golden statues of Buddha, located near the Monkey Temple. If you like less crowded places to peacefully enjoy a site and it’s surroundings. The Park in Kathmandu is the site of the largest Buddha statue in Nepal at 67 feet, and also two other Buddhas at 64 feet each. It is a relaxing place, not busy with tourists, at least when I was there, despite its location just off the bustling Ring Road of the city. The entrance is free of charge, and the religious concentration is flanked by parkland that is a welcome sight in what is often a traffic-clogged and dusty city. The location is also an excellent access point for Swayambhunath, or the monkey temple, with a direct walkway, lined with booths, connecting the two points.
    ','https://ktmguide.com/wp-content/uploads/2019/12/b0.jpg','5','https://ktmguide.com/listing/amideva-buddha-park/#group-2','https://ktmguide.com/listing/amideva-buddha-park/#group-3

    '),
    ('32', '27.701195723333','85.319914360606' ,'KATHMANDU FUN PARK','Kathmandu Fun Park is the biggest amusement park in Nepal offering varieties of activities including car skating, Columbus, train, tower game, Ferris wheel, helicopter for kids, boat games, bungee for kids, and more that are best suited for children and youngsters.

    Kathmandu Fun Park is located in the heart of the city making it easily accessible from all parts of Kathmandu valley. The park offers group discounts except during the public holidays which are often busy with visitors.

    ','https://ktmguide.com/wp-content/uploads/2019/12/xf2-2-550x410.jpg.pagespeed.ic.Rv87FX0IM9.webp
    ','6','https://ktmguide.com/wp-content/uploads/2019/12/xIMG_20210418_113129-01-550x410.jpeg.pagespeed.ic.YiSWLJaahh.webp
    ','https://ktmguide.com/wp-content/uploads/2019/12/xf3-2-550x410.jpg.pagespeed.ic.oN604lq9dd.webp'),
    ('33', '27.6664','85.2904
    ' ,'WHOOPEE LAND AMUSEMENT WATER PARK','Whoopee Land a modern amusement waterpark has come into operation in Chobhar, Kirtipur. The site is located 3.5 km from Balkhu. Innovation Pvt. Ltd. has invested 250 million rupees to bring this amusement park into operation. This park serves as a popular weekend getaway for people living in Kathmandu valley. This stunning fantasy world provides many facilities and places for children to enjoy activities such as slides, children’s playground,360 degrees Ranger, 180 degrees Frisbee, the bouncy Zorb ball along curvy meadows and Animatronics Dinosaurs. Non-stop aquatic thrill rides feature Multilane, high-Speed Slide, Family Raft, Space Bowl, Spectacular kids water-play fort Multipin Platform for kiddies. Aqua venture in the idyllic environment is perfect for all vacationers; thrill-seekers, and all age people. The water park offers an extreme level of excitement and delivers an “Aqua” Adventure unlike any other. Hold on as the Water Park slides takes your breath away at every turn, splash down on our slides. And don’t forget, The Bee Garden and dining area that can accommodate up to 200 guests for birthday parties, family reunions or any group outing.
    ','https://ktmguide.com/wp-content/uploads/2019/12/xw1-550x410.jpg.pagespeed.ic.P9B7dpBXJD.webp
    ','6','https://ktmguide.com/listing/amideva-buddha-park/#group-3','https://ktmguide.com/listing/amideva-buddha-park/#group-3'),
    ('34', '27.7161','85.2841' ,'AMIDEVA BUDDHA PARK','Amideva Buddha Park features three giant golden statues of Buddha, located near the Monkey Temple. If you like less crowded places to peacefully enjoy a site and it’s surroundings. The Park in Kathmandu is the site of the largest Buddha statue in Nepal at 67 feet, and also two other Buddhas at 64 feet each. It is a relaxing place, not busy with tourists, at least when I was there, despite its location just off the bustling Ring Road of the city. The entrance is free of charge, and the religious concentration is flanked by parkland that is a welcome sight in what is often a traffic-clogged and dusty city. The location is also an excellent access point for Swayambhunath, or the monkey temple, with a direct walkway, lined with booths, connecting the two points.
    ','https://ktmguide.com/wp-content/uploads/2019/12/b0.jpg','1','https://lexlimbu.com/wp-content/uploads/Whoopee-Land-Amusement-and-Water-Park-Nepal-5.jpg
    ','https://ktmguide.com/listing/whoopee-land-amusement-water-park/#group-1
    '),
    ('35', '27.7141','85.3145' ,'GARDEN OF DREAMS','The beautifully restored Swapna Bagaicha, also known as Garden of Dreams is a popular tourist place in Kathmandu to visit offers respite and rejuvenation from the stresses of the world. It is one of the most stunning places in the world. The garden was built in the 1920s and has been brought back to life by the Austrian financed team. The stunningly restored garden has gorgeous and refined details. Some of the main highlights of this place includes marble inscription from Omar Khayam’s Rubaiyat, beautiful fountains and ponds. The palace is home to a quirky ‘hidden garden’ as well. It also features three pavilions. The place is ideal for going out for a picnic or just to marvel at the human-nature interaction. The place is a must visit for travelers.
    ','
    https://ktmguide.com/listing/garden-of-dreams/#group-1','6',
    'https://ktmguide.com/listing/garden-of-dreams/#group-2','https://ktmguide.com/listing/garden-of-dreams/#group-3'),
    ('36', '27.659','85.2933' ,'MANJUSHREE PARK','Manjushree park is located in Chobhar gorge of Kirtipur municipality, which lies in the southern part of Kathmandu Valley. Chobhar gorge, where the Manjushree Cave is located, is related to the interesting legends of the origin of Kathmandu Valley. According to one of the legends, Kathmandu valley was a lake surrounded by hills during the Pleistocene era. It is believed that Manjushree, a divine saint from China had come here for pilgrimage and saw a huge lotus emanating bright light at the center of the lake. So he cut a deep gorge allowing the water to drain from the lake because he wanted to observe and worship the lotus.
    ','https://ktmguide.com/listing/manjushree-park/#group-1','6','https://ktmguide.com/listing/manjushree-park/#group-2
    ','https://ktmguide.com/listing/manjushree-park/#group-4'),
    ('37', '27.7344','85.3105' ,'BSR MOVIES ','BSR Movies is the first movie theatre in Kathmandu to introduce the Dolby Atmos sound system. Dolby Atmos renders everything from dialogue to quiet scenes to whirlwind action with astonishing clarity, richness, detail and depth. BSR movies has 2 screens with capacity of 166 seats for each screen.
    Location | BG Hall, Gongabu','
    https://www.oyektm.com/wp-content/uploads/2018/01/bsrmovies.jpg','8','https://www.oyektm.com/wp-content/uploads/2018/01/ini-cinemas.jpg','https://www.tourismkathmandu.com/images/classification/bsrmovies-p1.jpg
    '),
    ('38', '27.6993','85.3124' ,'QFX CINEMAS','It is a cinema chain in Nepal with theatres in major cities of Nepal. It features Nepali movies as well as Bollywood and Hollywood movies. QFX cinemas are so far the most preferred cinemas in the city with outlets in various locations and online booking and payment options which makes it more convenient for customers to make their bookings and purchase.
    Locations | Civil Mall (Sundhara), Labim Mall (Pulchowk), Kumari Hall (Putalisadak), Jai Nepal Hall (Narayanhiti Path).
    ','https://oyektm.com/wp-content/uploads/2020/11/912ad4_97c78ec98b084acabb5bd18e320d3a09mv2.jpg
    ','8','https://fastly.4sqi.net/img/general/600x600/7OSWVvpUsSets7yNcAS8phk4joR_aHpyWLqlrBKDQbc.jpg','https://www.oyektm.com/wp-content/uploads/2018/01/ini-cinemas.jpg
    '),
    ('39', '27.7094','85.3266' ,'BIG MOVIES','Big Movies is one of the best & Nepal’s First Multiplex operated by Bishal Group. It has 3 screens with a capacity of 870 seats providing world-class auditorium with Barco 2K latest Digital Projector Systems, Crystal Clear DTS sound, luxurious and comfortable seats and a wide-screen viewing experience.
    Location | City Center Mall, Kamalpokhari
    ','https://oyektm.com/wp-content/uploads/2020/11/912ad4_516ac66c165343fc8bef82bf93dfe161mv2.jpg
    ','8','https://oyektm.com/wp-content/uploads/2020/11/912ad4_ffc887823163472cb6cddef85f3cb7cfmv2.jpg
    ','https://bigmovies.com.np/Upload/images/Big%20Movies%20logo.jpg
    '),
    ('40', '27.7185','85.3499' ,'FCUBE CINEMAS','The Fcube cinema hall is one of the newer cinema halls in Kathmandu equipped with cutting edge technologies like Dolby 3 Ware Digital sound systems and digital 2K projection view. While all the other best theatres are situated in the busiest parts of the town, this theatre is based at the other side, making it convenient for people to watch movies without having to travel much.
    Location | KL Tower, Chabahil','https://oyektm.com/wp-content/uploads/2020/11/912ad4_d487827954544718b3ec3cdc3075a177mv2.jpg
    ','8','https://ktmguide.com/wp-content/uploads/2019/08/fcube3.jpg','https://ktmguide.com/wp-content/uploads/2019/08/FCUBECinemasNepal.png
    '),
    ('41', '27.6979','85.3129' ,'CINE DE CHEF','As their name suggests, Cine de Chef, are a combination of Cinema with Dining. When you watch movies with them, you are just not in a movie theatre, but you are in a cinematic hub, where you can enjoy all the facilities of 5-star restaurant serving, finger foods, Thai, French, Indian and Chef’s Special to add unparallel experience to movie watching.
    Location | Civil Trade Center, Sundhara
    ','https://ktmguide.com/listing/cdc-cinemas/#group-1','8','https://ktmguide.com/listing/cdc-cinemas/#group-2','https://ktmguide.com/listing/cdc-cinemas/#group-3');

    
    